2021-11-18 10:15:23 info: ---------------------------------------
2021-11-18 10:15:23 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-11-18 10:15:23 info: ---------------------------------------
2021-11-18 10:15:29 error: *** Unit Test Error Report ***

  console.log
    John Doe

      at 3-UsingAPIs/Week1/homework/ex1-johnWho.js:26:23


2021-11-18 10:18:34 info: ---------------------------------------
2021-11-18 10:18:34 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-11-18 10:18:34 info: ---------------------------------------
2021-11-18 10:18:38 error: *** Unit Test Error Report ***

  console.log
    John Doe

      at 3-UsingAPIs/Week1/homework/ex1-johnWho.js:26:23


2021-11-18 10:21:21 info: ---------------------------------------
2021-11-18 10:21:21 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-11-18 10:21:21 info: ---------------------------------------
2021-11-18 10:21:25 error: *** Unit Test Error Report ***

  console.log
    John Doe

      at 3-UsingAPIs/Week1/homework/ex1-johnWho.js:26:23


2021-11-18 10:23:00 info: ---------------------------------------
2021-11-18 10:23:00 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-11-18 10:23:00 info: ---------------------------------------
2021-11-18 10:23:00 info: Exercise has not yet been modified
2021-11-18 10:23:02 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-johnWho.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js
  getAnonName
    ✓ should exist and be executable (2 ms)
    ✕ should have all TODO comments removed (6 ms)
    ✕ should call `new Promise()` (1 ms)
    ✕ should take a single argument (1 ms)
    ✕ `resolve()` should be called with a one argument (1 ms)
    ✕ `reject()` should be called with a one argument
    ✕ should resolve when called with a string argument (1 ms)
    ✕ should reject with an Error object when called without an argument (1 ms)

  ● getAnonName › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      113 |
      114 | function checkTodos(source) {
    > 115 |   expect(source.includes('TODO')).toBeFalsy();
          |                                   ^
      116 | }
      117 |
      118 | module.exports = {

      at checkTodos (test-runner/unit-test-helpers.js:115:35)
      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:48:55)

  ● getAnonName › should call `new Promise()`

    expect(received).toBeDefined()

    Received: undefined

      49 |
      50 |   test('should call `new Promise()`', () => {
    > 51 |     expect(state.newPromise).toBeDefined();
         |                              ^
      52 |   });
      53 |
      54 |   test('should take a single argument', () => {

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:51:30)

  ● getAnonName › should take a single argument

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 2

      53 |
      54 |   test('should take a single argument', () => {
    > 55 |     expect(state.paramCount).toBe(1);
         |                              ^
      56 |   });
      57 |
      58 |   test('`resolve()` should be called with a one argument', () => {

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:55:30)

  ● getAnonName › `resolve()` should be called with a one argument

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: undefined

      57 |
      58 |   test('`resolve()` should be called with a one argument', () => {
    > 59 |     expect(state.resolve).toBe(1);
         |                           ^
      60 |   });
      61 |
      62 |   test('`reject()` should be called with a one argument', () => {

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:59:27)

  ● getAnonName › `reject()` should be called with a one argument

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: undefined

      61 |
      62 |   test('`reject()` should be called with a one argument', () => {
    > 63 |     expect(state.reject).toBe(1);
         |                          ^
      64 |   });
      65 |
      66 |   test('should resolve when called with a string argument', () => {

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:63:26)

  ● getAnonName › should resolve when called with a string argument

    expect(received).toBeInstanceOf(expected)

    Expected constructor: Promise

    Received value has no prototype
    Received value: undefined

      68 |     expect(exported).toBeDefined();
      69 |     const promise = getAnonName('John');
    > 70 |     expect(promise).toBeInstanceOf(Promise);
         |                     ^
      71 |     return expect(promise).resolves.toEqual('John Doe');
      72 |   });
      73 |

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:70:21)

  ● getAnonName › should resolve when called with a string argument

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      65 |
      66 |   test('should resolve when called with a string argument', () => {
    > 67 |     expect.assertions(3);
         |            ^
      68 |     expect(exported).toBeDefined();
      69 |     const promise = getAnonName('John');
      70 |     expect(promise).toBeInstanceOf(Promise);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:67:12)

  ● getAnonName › should reject with an Error object when called without an argument

    expect(received).toBeInstanceOf(expected)

    Expected constructor: Promise

    Received value has no prototype
    Received value: undefined

      76 |     expect(exported).toBeDefined();
      77 |     const promise = getAnonName();
    > 78 |     expect(promise).toBeInstanceOf(Promise);
         |                     ^
      79 |     return expect(promise).rejects.toBeInstanceOf(Error);
      80 |   });
      81 | });

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:78:21)

  ● getAnonName › should reject with an Error object when called without an argument

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      73 |
      74 |   test('should reject with an Error object when called without an argument', () => {
    > 75 |     expect.assertions(3);
         |            ^
      76 |     expect(exported).toBeDefined();
      77 |     const promise = getAnonName();
      78 |     expect(promise).toBeInstanceOf(Promise);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:75:12)

Test Suites: 1 failed, 1 total
Tests:       7 failed, 1 passed, 8 total
Snapshots:   0 total
Time:        1.094 s, estimated 3 s
Ran all test suites matching /ex1-johnWho.test.js/i.

2021-11-18 10:23:54 info: ---------------------------------------
2021-11-18 10:23:54 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-11-18 10:23:54 info: ---------------------------------------
2021-11-18 10:23:59 error: *** Unit Test Error Report ***

  console.log
    John Doe

      at 3-UsingAPIs/Week1/homework/ex1-johnWho.js:26:23


2021-11-18 10:24:27 info: -------------------------------------------------
2021-11-18 10:24:27 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2021-11-18 10:24:27 info: -------------------------------------------------
2021-11-18 10:24:30 error: *** Unit Test Error Report ***

  console.log
    This is a double digit number!

      at 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js:25:30

  console.log
    Expected a double digit number but got 5

      at 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js:30:29

  console.log
    Expected a double digit number but got 123

      at 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js:34:29


2021-11-18 10:25:58 info: ----------------------------------------
2021-11-18 10:25:58 info: >>> Running Unit Test `ex3-rollDice` <<<
2021-11-18 10:25:58 info: ----------------------------------------
2021-11-18 10:26:01 error: *** Unit Test Error Report ***

Command failed: npx jest ex3-rollDice.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex3-rollDice.test.js
  rollDice
    ✓ should exist and be executable (1 ms)
    ✕ should have all TODO comments removed (5 ms)
    ✓ should call `new Promise()`
    ✓ `resolve()` should be called with a one argument (1 ms)
    ✓ `reject()` should be called with a one argument
    ✓ should resolve when the dice settles successfully (1 ms)
    ✓ should reject with an Error when the dice rolls off the table (1 ms)

  ● rollDice › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      113 |
      114 | function checkTodos(source) {
    > 115 |   expect(source.includes('TODO')).toBeFalsy();
          |                                   ^
      116 | }
      117 |
      118 | module.exports = {

      at checkTodos (test-runner/unit-test-helpers.js:115:35)
      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex3-rollDice.test.js:39:55)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        1.106 s
Ran all test suites matching /ex3-rollDice.test.js/i.

2021-11-18 10:26:44 info: ----------------------------------------
2021-11-18 10:26:44 info: >>> Running Unit Test `ex3-rollDice` <<<
2021-11-18 10:26:44 info: ----------------------------------------
2021-11-18 10:26:46 info: All unit tests passed.
2021-11-18 10:26:48 info: All steps were completed successfully
2021-11-18 10:27:15 info: ----------------------------------------
2021-11-18 10:27:15 info: >>> Running Unit Test `ex3-rollDice` <<<
2021-11-18 10:27:15 info: ----------------------------------------
2021-11-18 10:27:17 info: All unit tests passed.
2021-11-18 10:27:19 info: All steps were completed successfully
2021-11-18 10:27:28 info: --------------------------------------------
2021-11-18 10:27:28 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-11-18 10:27:28 info: --------------------------------------------
2021-11-18 10:27:30 error: *** Unit Test Error Report ***

Command failed: npx jest ex4-pokerDiceAll.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js
  ex4-pokerDiceAll
    ✓ should exist and be executable (2 ms)
    ✕ should have all TODO comments removed (6 ms)
    ✓ should use `dices.map()` (1 ms)
    ✓ should use `Promise.all()`
    ✓ should resolve when all dices settle successfully (2 ms)
    ✓ should reject with an Error when a dice rolls off the table (2 ms)

  ● ex4-pokerDiceAll › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      113 |
      114 | function checkTodos(source) {
    > 115 |   expect(source.includes('TODO')).toBeFalsy();
          |                                   ^
      116 | }
      117 |
      118 | module.exports = {

      at checkTodos (test-runner/unit-test-helpers.js:115:35)
      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js:36:55)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 5 passed, 6 total
Snapshots:   0 total
Time:        1.077 s
Ran all test suites matching /ex4-pokerDiceAll.test.js/i.

2021-11-18 10:27:53 info: --------------------------------------------
2021-11-18 10:27:53 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-11-18 10:27:53 info: --------------------------------------------
2021-11-18 10:27:55 info: All unit tests passed.
2021-11-18 10:27:58 info: All steps were completed successfully
2021-11-18 10:28:08 info: ----------------------------------------------
2021-11-18 10:28:08 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2021-11-18 10:28:08 info: ----------------------------------------------
2021-11-18 10:28:11 error: *** Unit Test Error Report ***

Command failed: npx jest ex5-pokerDiceChain.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js
  ex5-pokerDiceChain
    ✓ should exist and be executable (1 ms)
    ✕ should have all TODO comments removed (7 ms)
    ✓ should resolve when all dices settle successfully (2 ms)
    ✓ should reject with an Error when a dice rolls off the table (1 ms)

  ● ex5-pokerDiceChain › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      113 |
      114 | function checkTodos(source) {
    > 115 |   expect(source.includes('TODO')).toBeFalsy();
          |                                   ^
      116 | }
      117 |
      118 | module.exports = {

      at checkTodos (test-runner/unit-test-helpers.js:115:35)
      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js:19:55)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 3 passed, 4 total
Snapshots:   0 total
Time:        1.367 s
Ran all test suites matching /ex5-pokerDiceChain.test.js/i.

2021-11-18 10:28:23 info: ----------------------------------------------
2021-11-18 10:28:23 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2021-11-18 10:28:23 info: ----------------------------------------------
2021-11-18 10:28:26 info: All unit tests passed.
2021-11-18 10:28:28 info: All steps were completed successfully
2021-11-18 10:28:43 info: ---------------------------------------
2021-11-18 10:28:43 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-11-18 10:28:43 info: ---------------------------------------
2021-11-18 10:28:47 info: All unit tests passed.
2021-11-18 10:28:49 info: All steps were completed successfully
2021-11-18 10:29:11 info: -------------------------------------------------
2021-11-18 10:29:11 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2021-11-18 10:29:11 info: -------------------------------------------------
2021-11-18 10:29:13 info: All unit tests passed.
2021-11-18 10:29:16 info: All steps were completed successfully
2021-11-18 10:29:47 info: ----------------------------------------
2021-11-18 10:29:47 info: >>> Running Unit Test `ex3-rollDice` <<<
2021-11-18 10:29:47 info: ----------------------------------------
2021-11-18 10:29:49 info: All unit tests passed.
2021-11-18 10:29:51 info: All steps were completed successfully
